# Workflow based on https://rust-lang.github.io/mdBook/continuous-integration.html

name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Install and run mdbook
        run: |
          mkdir bin
          cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
          cargo install mdbook-svgbob2
          bin/mdbook build
